### ISSUE TITLE
got a Reviewer

### ISSUE THREAD

**Issue by aindrajaya** [sutooy/sutofigmatoreact#1]
you can ask me as a reviewer to review this task. Thank you

**Comment by sutooy** [comment]
malam mas
aku dah setting collaborator mas, atau gmn mas

[image: image.png]

**Comment by aindrajaya** [comment]
@sutooy tempatnya reviewer di sebelah kanan mas haha

**Comment by sutooy** [comment]
@aindrajaya udah gini mas?

**Comment by aindrajaya** [comment]
okee sip mas, spertine ini aku salah set tugasnya, tp gpp. Thanks mas haha
